### ISSUE TITLE
Convert email nightlog exposure lists to tables, not graphics

### ISSUE THREAD

**Issue by sbailey** [desihub/desilo#33]
The desi-nightlog Night Summary emails (which I think are generated by inputs traced to desilo/DESI_Night_Logs) include the exposure list as attached pngs, which means that they aren't searchable, cut-and-pastable, and they include cut-off program names.  Please update to having those exposure lists as formatted table text within the email itself.

If this isn't the right place for tracking nightlog interface issues, please point me in the right direction.  Thanks.

**Comment by parfa30** [comment]
This is actually outside of the scope of the night log but I'm working on it.
